version: "{build}"
image: Visual Studio 2017
environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "1"
    DOTNET_CLI_TELEMETRY_OPTOUT: "1"
test: off
branches:
  only:
    - master
    - /^release\/.*$/
build_script:
  - ps: ./build.ps1
dotnet_csproj:
  patch: true
  file: 'src\**\*.csproj'
  version: "{version}"
  package_version: "{version}"
artifacts:
  - path: '**\*.nupkg'
install:
  # Push job information to Zeus
  - npm install -g @zeus-ci/cli
  - zeus job update --status=pending -B "%APPVEYOR_PULL_REQUEST_TITLE%" -J "%APPVEYOR_JOB_NAME%" ||
    echo "%$APPVEYOR_REPO_BRANCH%" | findstr /V "release/">nul
on_success:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      bash -c 'ls -alh; echo 123; pwd'
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "**\coverage.xml"

      Resolve-Path -Relative .\src\*\bin\Release\*.nupkg |
        Foreach-Object { zeus upload -t "application/zip+nupkg" $_};
      if ($?) { zeus job update --status=passed }
        else { $host.SetShouldExit(1) }
on_failure:
  - zeus job update --status=failed ||
    echo "%$APPVEYOR_REPO_BRANCH%" | findstr /V "release/">nul
