version: "{build}"
image: Visual Studio 2017
environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "1"
    DOTNET_CLI_TELEMETRY_OPTOUT: "1"
test: off
branches:
  only:
    - master
    - /^release\/.*$/
build_script:
  - ps: ./build.ps1
dotnet_csproj:
  patch: true
  file: 'src\**\*.csproj'
  version: "{version}"
  package_version: "{version}"
artifacts:
  - path: '**\*.nupkg'
install:
  # Push job information to Zeus
  - npm install -g @zeus-ci/cli
  - C:\msys64\usr\bin\bash scripts\zeus.sh report_pending
on_success:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "**\coverage.xml"

      # Upload *.nupkg files to Zeus
      bash scripts/zeus.sh upload_artifacts
on_failure:
  - C:\msys64\usr\bin\bash scripts\zeus.sh report_failed
