version: "{build}"
image: Visual Studio 2019
environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "1" # Used by the dotnet SDK prior to v3.0
    DOTNET_CLI_TELEMETRY_OPTOUT: "1"
  PREVIEW_DOTNET: "5.0.100"
branches:
  only:
    - main
    - /^release\/.*$/

install:
  - cmd: git submodule update --init --recursive
  - ps: New-Item -Path '.tmp' -ItemType Directory
  - ps: "[Net.ServicePointManager]::SecurityProtocol = 'Tls12'"
  - ps: Invoke-WebRequest https://dot.net/v1/dotnet-install.ps1 -OutFile .tmp\dotnet-install.ps1
  - ps: if ((-Not (Test-Path .tmp\dotnet\dotnet.exe)) -or (((.tmp\dotnet\dotnet.exe --version) -Join '') -ne $Env:PREVIEW_DOTNET)) { .tmp\dotnet-install.ps1 -Version $Env:PREVIEW_DOTNET -InstallDir .tmp\dotnet } else { $Env:path = $Env:APPVEYOR_BUILD_FOLDER + "\.tmp\dotnet\dotnet.exe;" + $Env:path }
test: off
build_script:
  - ps: ./build.ps1
dotnet_csproj:
  patch: true
  file: 'src\**\*.csproj'
  version: "{version}"
  package_version: "{version}"
artifacts:
  - path: 'src\**\Release\*.nupkg'
  - path: 'src\**\Release\*.snupkg'
