language: csharp
install:
  - curl -L https://dot.net/v1/dotnet-install.sh > /tmp/install-dotnet.sh && bash /tmp/install-dotnet.sh -Version 1.1.8
  - sudo mv ~/.dotnet/shared/Microsoft.NETCore.App/* "$(dirname $(dirname $(dotnet --info | grep "Base Path" | awk '{print $3}')))/shared/Microsoft.NETCore.App/"
  - sudo mv ~/.dotnet/sdk/* "$(dirname $(dirname $(dotnet --info | grep "Base Path" | awk '{print $3}')))/sdk/"
  - npm install -g @zeus-ci/cli
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
dotnet: 2.1.103
mono: 5.12.0
matrix:
  include:
    - os: osx # osx_image: xcode8.3 Default	Xcode 8.3.3	OS X 10.12	1.8.0_112-b16
      osx_image: xcode9.2
    - os: linux
      dist: trusty
      sudo: required
      group: edge
script:
  - ./build.sh

branches:
  only:
    - master
    - /^release\/.*$/

notifications:
  webhooks:
    urls:
      - https://zeus.ci/hooks/94196268-8f31-11e8-87bb-0a580a280341/public/provider/travis/webhook
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
