language: csharp
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1 # Used by the dotnet SDK prior to v3.0
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
mono: 6.6.0
branches:
  only:
    - master
    - /^release\/.*$/
matrix:
  include:
    - os: osx
      osx_image: xcode11.2
    - os: linux
      dist: bionic
      sudo: required
      group: edge
script:
  - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version 2.1.507
  - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version 3.1.100
  - export PATH=$PATH:~/.dotnet
  - dotnet --info
  - ./build.sh
after_success:
  - curl -s https://codecov.io/bash > codecov
  - chmod +x codecov
  - ./codecov -f "*opencover.xml"
notifications:
  webhooks:
    urls:
      - https://zeus.ci/hooks/b6bbaf86-c598-11e8-aa19-0a580a280112/public/provider/travis/webhook
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
